import Head from 'next/head'
import styles from '../styles/Connexion.module.css'
import { Grid } from "@mui/material";

export default function Connexion() {
    return (
        <div className='container'>
            <Head>
                <title>Résilience 34 - Connexion</title>
                <meta name='description' content='Generated by create next app' />
            </Head>
            <Grid container item xs={8} className={styles.formulaire}>
                <Grid item xs={12}>
                    <h2>
                        Veuillez vous connecter pour accéder au réseau de la clinique
                    </h2>
                    <form>
                        <input id="name" type="text" placeholder="nom" required />
                        <br />
                        <input id="email" type="email" placeholder="email" required />
                        <br />
                        <button type="submit">Connexion</button>
                    </form>
                </Grid>
            </Grid>
        </div>
    )
}
