import Head from 'next/head'
import styles from '../styles/Contact.module.css'
import { Grid } from "@mui/material";

export default function Contact() {
    return (
        <div className='container'>
            <Head>
                <title>Résilience 34 - Contact</title>
                <meta name='description' content='Generated by create next app' />
            </Head>
            <Grid container item xs={8} className={styles.informations}>
                <Grid item xs={12}>
                    Coordonnées
                </Grid>
            </Grid>
        </div>
    )
}
