import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router";
import { Grid } from "@mui/material";

const link = ({children, href}) => {
  const router = useRouter()
  return (
    <a href='#'
    onClick={e => {
      e.preventDefault()
      router.push(href)
    }}
    >{children}</a>
  )
}

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Résilience 34</title>
        <meta name='description' content='Generated by create next app'/>
      </Head>
      <Grid container item xs={4} direction='column' className={styles.welcome}>
        <Grid item xs={12}>
          Bienvenue
        </Grid>
        <Grid item xs={12}>
          sur
        </Grid>
        <Grid item xs={12} className={styles.welcome_span}>
          Résilience 34
        </Grid>
      </Grid>
    </div>
  )
}
